### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by jimmywarting** [WICG/navigation-api#233]
I like this new navigation api. specially the part about adding a event listener and using abort signal. 
Now we just need to be able to use `import(url, { signal})` too

just wondering if anyone have built any polyfill for this already?

**Comment by domenic** [comment]
Glad to hear you like it!

The polyfill I'm aware of is https://github.com/virtualstate/navigation , although I haven't tried it myself.

**Comment by jimmywarting** [comment]
Ty, will try it out tomorrow

**Comment by jimmywarting** [comment]
tried it out... it was quite large in size. and it didn't work... it was broken. 

I will stick to history api in the meantime until all browser adds support for this new api
